version: '3.5'

services:
  portainer:
    image: portainer/portainer:1.24.1-alpine
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - 8181:9000
    volumes:
      - portainer:/data
    deploy:
      labels:
        - caddy=http://portainer.${CLUSTER_DOMAIN} https://portainer.${CLUSTER_DOMAIN}
        - caddy.reverse_proxy={{upstreams 9000}}
        - caddy.encode=gzip
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - caddy
      - admin

  portainer-agent:
    image: portainer/agent:linux-amd64-1.6.0-alpine
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - admin
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

  dashboard:
    image: charypar/swarm-dashboard:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 8282:8080
    environment:
      - PORT=8080
    deploy:
      labels:
        - caddy=http://dashboard.${CLUSTER_DOMAIN} https://dashboard.${CLUSTER_DOMAIN}
        - caddy.reverse_proxy={{upstreams 8080}}
        - caddy.encode=gzip
        - caddy.basicauth=/*
        - caddy.basicauth.admin=JDJhJDEwJGZFS3ZIdFpIek9sNG1RMk5zQm0xVnV5S2VyQkJPS3lRV3h0Y1pwSTA4cUNFd1IwcVFNMGxP
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - caddy

  swarmpit:
    image: swarmpit/swarmpit:1.9
    # environment:
    #   - SWARMPIT_DB=http://db:5984
    #   - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - caddy
      - admin
    deploy:
      labels:
        - caddy=http://swarmpit.${CLUSTER_DOMAIN} https://swarmpit.${CLUSTER_DOMAIN}
        - caddy.reverse_proxy={{upstreams 8080}}
        - caddy.encode=gzip
        - caddy.basicauth=/*
        - caddy.basicauth.admin=JDJhJDEwJGZFS3ZIdFpIek9sNG1RMk5zQm0xVnV5S2VyQkJPS3lRV3h0Y1pwSTA4cUNFd1IwcVFNMGxP
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  swarmpit-agent:
    image: swarmpit/agent:2.2
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - admin
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

  feeds:
    image: flaviostutz/docker-swarm-feeds:1.1.0
    # ports:
    #   - 5353:8000
    environment:
      - FEED_NAME=${CLUSTER_DOMAIN}
    deploy:
      labels:
        - caddy=http://feeds.${CLUSTER_DOMAIN} https://feeds.${CLUSTER_DOMAIN}
        - caddy.reverse_proxy={{upstreams 8000}}
        - caddy.encode=gzip
        - caddy.basicauth=/*
        - caddy.basicauth.admin=JDJhJDEwJGZFS3ZIdFpIek9sNG1RMk5zQm0xVnV5S2VyQkJPS3lRV3h0Y1pwSTA4cUNFd1IwcVFNMGxP
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  janitor:
    image: flaviostutz/docker-janitor:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - SLEEP_TIME=86400
      - UNUSED_TIME=24h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  admin:
    external: true
    # driver: overlay
    # "docker network create admin --scope swarm -d overlay"
  caddy:
    external: true

volumes:
  portainer:
