version: '3.5'

services:
  helloworld:
    image: whalesalad/docker-debug
    networks:
      - caddy
    deploy:
      labels:
        - caddy=helloworld.mycluster.org
        - caddy.tls=internal
        - caddy.reverse_proxy={{upstreams 8080}}
        - caddy.encode=gzip
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  caddy:
    external: true
